FROM node:22-alpine AS builder
WORKDIR /app

COPY . .

RUN corepack enable
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @photobank/telegram-bot build

FROM node:22-alpine AS runner
WORKDIR /app

COPY . .

RUN corepack enable
RUN pnpm install --prod

COPY --from=builder /app/packages/telegram-bot/dist ./packages/telegram-bot/dist

CMD ["node", "packages/telegram-bot/dist/index.js"]
