services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_EMAIL=${API_EMAIL}
      - API_PASSWORD=${API_PASSWORD}
      - API_BASE_URL=http://host.docker.internal:5066