services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_BASE_URL: ${API_BASE_URL}
    ports:
      - "5173:5173"
    restart: always
    environment:
      - VITE_API_BASE_URL=http://192.168.1.63:5066 # проброс в Docker

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_EMAIL=${API_EMAIL}
      - API_PASSWORD=${API_PASSWORD}
      - VITE_API_BASE_URL=http://192.168.1.63:5066