steps:
  - name: backend-build-test
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - echo "Backend restore build test"
      - dotnet --version
      - cd backend
      - dotnet restore PhotoBank.Backend.sln
      - dotnet build PhotoBank.Backend.sln --no-restore --configuration Release
      - dotnet test PhotoBank.Backend.sln --no-build --configuration Release --verbosity normal