steps:
  - name: frontend-build-test
    image: node:20-alpine
    commands:
      - echo "Install dependencies"
      - cd frontend
      - corepack enable
      - pnpm install --frozen-lockfile
      - pnpm -r --if-present build
      - pnpm -r --if-present test
