steps:
  - name: frontend-build-test
    image: node:20-alpine
    commands:
      - echo "Frontend install build test"
      - cd frontend
      - corepack enable
      - pnpm install --frozen-lockfile
      - pnpm build
      - pnpm test