steps:
  - name: backend-build
    image: mcr.microsoft.com/dotnet/sdk:9.0
    commands:
      - echo "Backend build and test"
      - cd backend
      - dotnet restore PhotoBank.Backend.sln
      - dotnet build PhotoBank.Backend.sln --no-restore --configuration Release
      - dotnet test PhotoBank.Backend.sln --no-build --configuration Release --filter "FullyQualifiedName~PhotoBank.UnitTests" || echo "⚠️ Backend tests failed, ignoring"

  - name: frontend-build
    image: node:20-alpine
    environment:
      VITE_API_BASE_URL:
        from_secret: vite_api_base_url
    commands:
      - echo "Frontend install build and test"
      - cd frontend
      - corepack enable
      - pnpm install --frozen-lockfile
      - pnpm build
      - pnpm test || echo "⚠️ Frontend tests failed, ignoring"

  - name: docker-compose-build
    image: docker:24.0.7-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      VITE_API_BASE_URL:
        from_secret: vite_api_base_url
    commands:
      - echo "Docker Compose build and push start"
      - docker version
      - docker info
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker compose build --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL
      - docker compose push
      - docker logout