/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import type {
  PersonGroupFaceDto
} from '../photoBankApiVersion1000CultureNeutralPublicKeyTokenNull.schemas';

import { photobankAxios } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getPersonGroupFaces = () => {
const personGroupFacesGetAll = (
    
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<PersonGroupFaceDto[]>(
      {url: `/persongroupfaces`, method: 'GET'
    },
      options);
    }
  const personGroupFacesCreate = (
    personGroupFaceDto: PersonGroupFaceDto,
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<PersonGroupFaceDto>(
      {url: `/persongroupfaces`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: personGroupFaceDto
    },
      options);
    }
  const personGroupFacesUpdate = (
    id: number,
    personGroupFaceDto: PersonGroupFaceDto,
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<PersonGroupFaceDto>(
      {url: `/persongroupfaces/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: personGroupFaceDto
    },
      options);
    }
  const personGroupFacesDelete = (
    id: number,
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<null>(
      {url: `/persongroupfaces/${id}`, method: 'DELETE'
    },
      options);
    }
  return {personGroupFacesGetAll,personGroupFacesCreate,personGroupFacesUpdate,personGroupFacesDelete}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type PersonGroupFacesGetAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPersonGroupFaces>['personGroupFacesGetAll']>>>
export type PersonGroupFacesCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPersonGroupFaces>['personGroupFacesCreate']>>>
export type PersonGroupFacesUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPersonGroupFaces>['personGroupFacesUpdate']>>>
export type PersonGroupFacesDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPersonGroupFaces>['personGroupFacesDelete']>>>
