/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api
 * OpenAPI spec version: 1.0.0
 */
import { customFetcher } from '../../../../../shared/src/api/photobank/fetcher';

export type versionGetResponse200 = {
  data: string;
  status: 200;
};

export type versionGetResponseComposite = versionGetResponse200;

export type versionGetResponse = versionGetResponseComposite & {
  headers: Headers;
};

export const getVersionGetUrl = () => {
  return `/version`;
};

export const versionGet = async (
  options?: RequestInit
): Promise<versionGetResponse> => {
  return customFetcher<versionGetResponse>(getVersionGetUrl(), {
    ...options,
    method: 'GET',
  });
};
