// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Metadata;
using PhotoBank.DbContext.DbContext;

#nullable disable

namespace PhotoBank.DbContext.Migrations
{
    [DbContext(typeof(PhotoBankDbContext))]
    [Migration("20250828194600_MakeFaceImageNullable")]
    partial class MakeFaceImageNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Intentionally left empty. Model snapshot is in PhotoBankDbContextModelSnapshot.
#pragma warning restore 612, 618
        }
    }
}
