// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using PhotoBank.DbContext.DbContext;

#nullable disable

namespace PhotoBank.DbContext.Migrations
{
    [DbContext(typeof(PhotoBankDbContext))]
    [Migration("20250815191236_SwitchTelegramToTelegramUserId")]
    partial class SwitchTelegramToTelegramUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhotoBank.DbContext.Models.ApplicationUser", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("nvarchar(450)");

                b.Property<long?>("TelegramUserId")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("TelegramUserId")
                    .IsUnique()
                    .HasFilter("[TelegramUserId] IS NOT NULL");

                b.ToTable("AspNetUsers");
            });
#pragma warning restore 612, 618
        }
    }
}
