/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import type {
  TagDto
} from '.././model';
import { customFetcher } from '.././fetcher';

export type tagsGetAllResponse200 = {
  data: TagDto[]
  status: 200
}
    
export type tagsGetAllResponseComposite = tagsGetAllResponse200;
    
export type tagsGetAllResponse = tagsGetAllResponseComposite & {
  headers: Headers;
}

export const getTagsGetAllUrl = () => {


  

  return `/api/tags`
}

export const tagsGetAll = async ( options?: RequestInit): Promise<tagsGetAllResponse> => {
  
  return customFetcher<tagsGetAllResponse>(getTagsGetAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


