/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * PhotoBank.Api
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  FaceDto,
  FaceDtoPageResponse,
  FacesGetAllParams,
} from '../photoBankApi.schemas';

import { customFetcher } from '.././fetcher';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type facesGetAllResponse200 = {
  data: FaceDtoPageResponse;
  status: 200;
};

export type facesGetAllResponseSuccess = facesGetAllResponse200 & {
  headers: Headers;
};
export type facesGetAllResponse = facesGetAllResponseSuccess;

export const getFacesGetAllUrl = (params?: FacesGetAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/faces?${stringifiedParams}`
    : `/faces`;
};

export const facesGetAll = async (
  params?: FacesGetAllParams,
  options?: RequestInit
): Promise<facesGetAllResponse> => {
  return customFetcher<facesGetAllResponse>(getFacesGetAllUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getFacesGetAllQueryKey = (params?: FacesGetAllParams) => {
  return [`/faces`, ...(params ? [params] : [])] as const;
};

export const getFacesGetAllQueryOptions = <
  TData = Awaited<ReturnType<typeof facesGetAll>>,
  TError = unknown,
>(
  params?: FacesGetAllParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof facesGetAll>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetcher>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFacesGetAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof facesGetAll>>> = () =>
    facesGetAll(params, requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof facesGetAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type FacesGetAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof facesGetAll>>
>;
export type FacesGetAllQueryError = unknown;

export function useFacesGetAll<
  TData = Awaited<ReturnType<typeof facesGetAll>>,
  TError = unknown,
>(
  params?: FacesGetAllParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof facesGetAll>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetcher>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getFacesGetAllQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type facesUpdateResponse200 = {
  data: void;
  status: 200;
};

export type facesUpdateResponseSuccess = facesUpdateResponse200 & {
  headers: Headers;
};
export type facesUpdateResponse = facesUpdateResponseSuccess;

export const getFacesUpdateUrl = () => {
  return `/faces`;
};

export const facesUpdate = async (
  faceDto: FaceDto,
  options?: RequestInit
): Promise<facesUpdateResponse> => {
  return customFetcher<facesUpdateResponse>(getFacesUpdateUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(faceDto),
  });
};

export const getFacesUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof facesUpdate>>,
    TError,
    { data: FaceDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetcher>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof facesUpdate>>,
  TError,
  { data: FaceDto },
  TContext
> => {
  const mutationKey = ['facesUpdate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof facesUpdate>>,
    { data: FaceDto }
  > = (props) => {
    const { data } = props ?? {};

    return facesUpdate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FacesUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof facesUpdate>>
>;
export type FacesUpdateMutationBody = FaceDto;
export type FacesUpdateMutationError = unknown;

export const useFacesUpdate = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof facesUpdate>>,
    TError,
    { data: FaceDto },
    TContext
  >;
  request?: SecondParameter<typeof customFetcher>;
}): UseMutationResult<
  Awaited<ReturnType<typeof facesUpdate>>,
  TError,
  { data: FaceDto },
  TContext
> => {
  const mutationOptions = getFacesUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
