import { setupWorker } from 'msw';
// Reuse the aggregated handlers generated by orval + our scenarios
import { handlers } from '@photobank/shared/api/photobank/msw';

export const worker = setupWorker(...handlers);
