/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import type {
  UpdateFaceDto
} from '../photoBankApiVersion1000CultureNeutralPublicKeyTokenNull.schemas';

import { photobankAxios } from '../../axios-instance';



  export const getFaces = () => {
const facesUpdate = (
    updateFaceDto: UpdateFaceDto,
 ) => {
      return photobankAxios<null>(
      {url: `/faces`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateFaceDto
    },
      );
    }
  return {facesUpdate}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type FacesUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFaces>['facesUpdate']>>>
