/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api
 * OpenAPI spec version: 1.0.0
 */
import type { FaceDto } from '../photoBankApi.schemas';

import { photobankAxios } from '../../axios-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getFaces = () => {
  const facesGetAll = (options?: SecondParameter<typeof photobankAxios>) => {
    return photobankAxios<FaceDto[]>({ url: `/faces`, method: 'GET' }, options);
  };
  const facesUpdate = (
    faceDto: FaceDto,
    options?: SecondParameter<typeof photobankAxios>
  ) => {
    return photobankAxios<null>(
      {
        url: `/faces`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: faceDto,
      },
      options
    );
  };
  return { facesGetAll, facesUpdate };
};
export type FacesGetAllResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFaces>['facesGetAll']>>
>;
export type FacesUpdateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFaces>['facesUpdate']>>
>;
