/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';

import type {
  FaceIdentityDto
} from '../photoBankApi.schemas';


export const getFacesGetResponseMock = (): FaceIdentityDto[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), undefined]), identityStatus: faker.helpers.arrayElement([faker.helpers.arrayElement([0,1,2,3,4,5] as const), undefined]), person: faker.helpers.arrayElement([{id: faker.number.int({min: undefined, max: undefined, multipleOf: undefined}), name: faker.string.alpha({length: {min: 1, max: 20}})}, undefined])})))


export const getFacesGetMockHandler = (overrideResponse?: FaceIdentityDto[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<FaceIdentityDto[]> | FaceIdentityDto[])) => {
  return http.get('/api/faces', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getFacesGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getFacesUpdateMockHandler = (overrideResponse?: null | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<null> | null)) => {
  return http.put('/api/faces', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}

export const getFacesGetImageMockHandler = (overrideResponse?: null | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<null> | null)) => {
  return http.get('/api/faces/:id/image', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}
export const getFacesMock = () => [
  getFacesGetMockHandler(),
  getFacesUpdateMockHandler(),
  getFacesGetImageMockHandler()]
