/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import type {
  ClaimDto,
  LoginRequestDto,
  LoginResponseDto,
  RegisterRequestDto,
  RoleDto,
  TelegramExchangeRequest,
  TelegramExchangeResponse,
  UpdateUserDto,
  UserDto
} from '../photoBankApiVersion1000CultureNeutralPublicKeyTokenNull.schemas';

import { photobankAxios } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getAuth = () => {
const authLogin = (
    loginRequestDto: LoginRequestDto,
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<LoginResponseDto>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequestDto
    },
      options);
    }
  const authRegister = (
    registerRequestDto: RegisterRequestDto,
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<null>(
      {url: `/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerRequestDto
    },
      options);
    }
  const authGetUser = (
    
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<UserDto>(
      {url: `/auth/user`, method: 'GET'
    },
      options);
    }
  const authUpdateUser = (
    updateUserDto: UpdateUserDto,
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<null>(
      {url: `/auth/user`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateUserDto
    },
      options);
    }
  const authTelegramExchange = (
    telegramExchangeRequest: TelegramExchangeRequest,
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<TelegramExchangeResponse>(
      {url: `/auth/telegram/exchange`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: telegramExchangeRequest
    },
      options);
    }
  const authGetUserClaims = (
    
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<ClaimDto[]>(
      {url: `/auth/claims`, method: 'GET'
    },
      options);
    }
  const authGetUserRoles = (
    
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<RoleDto[]>(
      {url: `/auth/roles`, method: 'GET'
    },
      options);
    }
  const authGetEffective = (
    
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<null>(
      {url: `/auth/debug/effective-access`, method: 'GET'
    },
      options);
    }
  return {authLogin,authRegister,authGetUser,authUpdateUser,authTelegramExchange,authGetUserClaims,authGetUserRoles,authGetEffective}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type AuthLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['authLogin']>>>
export type AuthRegisterResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['authRegister']>>>
export type AuthGetUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['authGetUser']>>>
export type AuthUpdateUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['authUpdateUser']>>>
export type AuthTelegramExchangeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['authTelegramExchange']>>>
export type AuthGetUserClaimsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['authGetUserClaims']>>>
export type AuthGetUserRolesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['authGetUserRoles']>>>
export type AuthGetEffectiveResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['authGetEffective']>>>
