/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import type {
  PathDto
} from '.././model';
import { customFetcher } from '.././fetcher';

export type pathsGetAllResponse200 = {
  data: PathDto[]
  status: 200
}
    
export type pathsGetAllResponseComposite = pathsGetAllResponse200;
    
export type pathsGetAllResponse = pathsGetAllResponseComposite & {
  headers: Headers;
}

export const getPathsGetAllUrl = () => {


  

  return `/api/paths`
}

export const pathsGetAll = async ( options?: RequestInit): Promise<pathsGetAllResponse> => {
  
  return customFetcher<pathsGetAllResponse>(getPathsGetAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


