/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api
 * OpenAPI spec version: 1.0.0
 */
import type {
  TagDto
} from '../photoBankApi.schemas';

import { photobankAxios } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getTags = () => {
const tagsGetAll = (
    
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<TagDto[]>(
      {url: `/tags`, method: 'GET'
    },
      options);
    }
  return {tagsGetAll}};
export type TagsGetAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTags>['tagsGetAll']>>>
