/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import type {
  TagDto
} from '../photoBankApiVersion1000CultureNeutralPublicKeyTokenNull.schemas';

import { photobankAxios } from '../../axios-instance';



  export const getTags = () => {
const tagsGetAll = (
    
 ) => {
      return photobankAxios<TagDto[]>(
      {url: `/tags`, method: 'GET'
    },
      );
    }
  return {tagsGetAll}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type TagsGetAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTags>['tagsGetAll']>>>
