/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import type {
  StorageDto
} from '../photoBankApiVersion1000CultureNeutralPublicKeyTokenNull.schemas';

import { photobankAxios } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getStorages = () => {
const storagesGetAll = (
    
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<StorageDto[]>(
      {url: `/storages`, method: 'GET'
    },
      options);
    }
  return {storagesGetAll}};
export type StoragesGetAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStorages>['storagesGetAll']>>>
