/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import type {
  StorageDto
} from '../photoBankApiVersion1000CultureNeutralPublicKeyTokenNull.schemas';

import { photobankAxios } from '../../axios-instance';



  export const getStorages = () => {
const storagesGetAll = (
    
 ) => {
      return photobankAxios<StorageDto[]>(
      {url: `/storages`, method: 'GET'
    },
      );
    }
  return {storagesGetAll}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type StoragesGetAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getStorages>['storagesGetAll']>>>
