/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api
 * OpenAPI spec version: 1.0.0
 */
import type { StorageDto } from '../photoBankApi.schemas';

import { customFetcher } from '../../../../../shared/src/api/photobank/fetcher';

export type getStoragesResponse200 = {
  data: StorageDto[];
  status: 200;
};

export type getStoragesResponseComposite = getStoragesResponse200;

export type getStoragesResponse = getStoragesResponseComposite & {
  headers: Headers;
};

export const getGetStoragesUrl = () => {
  return `/Storages`;
};

export const getStorages = async (
  options?: RequestInit
): Promise<getStoragesResponse> => {
  return customFetcher<getStoragesResponse>(getGetStoragesUrl(), {
    ...options,
    method: 'GET',
  });
};
