/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api
 * OpenAPI spec version: 1.0.0
 */
import type { PathDto } from '../photoBankApi.schemas';

import { photobankAxios } from '../../axios-instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getPaths = () => {
  const getPaths = (options?: SecondParameter<typeof photobankAxios>) => {
    return photobankAxios<PathDto[]>({ url: `/Paths`, method: 'GET' }, options);
  };
  return { getPaths };
};
export type GetPathsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPaths>['getPaths']>>
>;
