/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import type {
  PathDto
} from '../photoBankApiVersion1000CultureNeutralPublicKeyTokenNull.schemas';

import { photobankAxios } from '../../axios-instance';



  export const getPaths = () => {
const pathsGetAll = (
    
 ) => {
      return photobankAxios<PathDto[]>(
      {url: `/paths`, method: 'GET'
    },
      );
    }
  return {pathsGetAll}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type PathsGetAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPaths>['pathsGetAll']>>>
