/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import type { FaceBoxDto } from './faceBoxDto';

export interface FaceDto {
  id?: number;
  /** @nullable */
  personId?: number | null;
  /** @nullable */
  age?: number | null;
  /** @nullable */
  gender?: boolean | null;
  /** @nullable */
  faceAttributes?: string | null;
  faceBox: FaceBoxDto;
  /** @minLength 1 */
  friendlyFaceAttributes: string;
}
