/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import type { TagItemDto } from './tagItemDto';
import type { PersonItemDto } from './personItemDto';

export interface PhotoItemDto {
  id: number;
  thumbnail?: string;
  thumbnailUrl?: string;
  previewUrl?: string;
  originalUrl?: string;
  /** @minLength 1 */
  name: string;
  /** @nullable */
  takenDate?: string | null;
  isBW?: boolean;
  isAdultContent?: boolean;
  adultScore?: number;
  isRacyContent?: boolean;
  racyScore?: number;
  /** @minLength 1 */
  storageName: string;
  /** @minLength 1 */
  relativePath: string;
  /** @nullable */
  tags?: TagItemDto[] | null;
  /** @nullable */
  persons?: PersonItemDto[] | null;
  /** @nullable */
  captions?: string[] | null;
}
