/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import type { PageResponseOfPhotoItemDto } from './pageResponseOfPhotoItemDto';
import type { QueryResultAllOf } from './queryResultAllOf';

export type QueryResult = PageResponseOfPhotoItemDto & QueryResultAllOf;
