kind: pipeline
name: frontend

# Для volume-кэша нужен trusted-режим для репозитория
volumes:
  - name: npm-cache
    host:
      path: /var/lib/woodpecker-cache/npm

steps:
  - name: build
    image: node:22-alpine
    when:
      event: [cron, manual]
      path: ['frontend/packages/frontend/*', 'frontend/packages/shared/*']
    environment:
      VITE_API_BASE_URL:
        from_secret: vite_api_base_url
    volumes:
      - name: npm-cache
        path: /root/.npm
    commands:
      - |
        echo "Changes in frontend detected — running build"
        cd frontend
        npm ci --prefer-offline
        npm run build

  - name: dockerize
    image: quay.io/thegeeklab/wp-docker-buildx
    privileged: true
    when:
      event: [push, tag, cron, manual]
      path: ['frontend/packages/frontend/*', 'frontend/packages/shared/*']
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: makhin/photobank-frontend
      tags:
        - latest
      context: frontend
      containerfile: frontend/Dockerfile.frontend
      pull_image: true
      provenance: false
      build_args:
        VITE_API_BASE_URL:
          from_secret: vite_api_base_url
      cache_from:
        - "type=registry,ref=makhin/photobank-frontend:buildcache"
      cache_to: "type=registry,ref=makhin/photobank-frontend:buildcache,mode=max"
