kind: pipeline
type: docker
name: frontend

when:
  - event: [push, manual]

steps:
  - name: build
    image: node:20-alpine
    environment:
      VITE_API_BASE_URL:
        from_secret: vite_api_base_url
    commands:
      - echo "Frontend install, build and test"
      - cd frontend
      - corepack enable
      - pnpm install --frozen-lockfile
      - pnpm --filter @photobank/frontend build
      - pnpm --filter @photobank/frontend test || echo "Frontend tests failed, ignoring"

  - name: publish
    image: docker:24.0.7-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
      VITE_API_BASE_URL:
        from_secret: vite_api_base_url
    commands:
      - echo "Frontend docker build and push"
      - docker version
      - docker info
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -f frontend/Dockerfile.frontend -t makhin/photobank-frontend:latest --build-arg VITE_API_BASE_URL=$VITE_API_BASE_URL frontend
      - docker push makhin/photobank-frontend:latest
      - docker logout