kind: pipeline          # тип конфигурации
name: bot          # имя pipeline (обязательно)

steps:
  - name: restore-pnpm-cache
    image: woodpeckerci/plugin-cache
    settings:
      restore: true
      mount:
        - /root/.local/share/pnpm/store

  - name: build
    image: node:22-alpine
    when:
      event: [cron, manual]
      path: ['frontend/packages/telegram-bot/**', 'frontend/packages/shared/**']
    environment:
      VITE_API_BASE_URL:
        from_secret: vite_api_base_url
    commands:
      - |
          echo "Changes in bot detected — running build"
          echo "Telegram bot install, build and test"
          cd frontend
          corepack enable
          pnpm install --frozen-lockfile
          pnpm --filter @photobank/telegram-bot build
          pnpm --filter @photobank/telegram-bot test || echo "Telegram bot tests failed, ignoring"

  - name: save-nuget-cache          # ← сохраняем NuGet‑кэш
    image: woodpeckerci/plugin-cache
    settings:
      rebuild: true
      mount:
        - /root/.nuget/packages

  - name: publish
    image: docker:28.4.0-cli
    when:
      event: [cron, manual]
      path: ['frontend/packages/telegram-bot/*', 'frontend/packages/shared/*']
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - |
          echo "Changes in bot detected — running build"
          echo "Telegram bot docker build and push"
          docker version
          docker info
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -f frontend/Dockerfile.bot -t makhin/photobank-bot:latest frontend
          docker push makhin/photobank-bot:latest
          docker logout


