/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import type {
  CreateUserDto,
  ResetPasswordDto,
  SetRolesDto,
  UpdateUserDto,
  UserDto
} from '../photoBankApiVersion1000CultureNeutralPublicKeyTokenNull.schemas';

import { photobankAxios } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getUsers = () => {
const usersGetAll = (
    
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<UserDto[]>(
      {url: `/admin/users`, method: 'GET'
    },
      options);
    }
  const usersCreate = (
    createUserDto: CreateUserDto,
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<UserDto>(
      {url: `/admin/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserDto
    },
      options);
    }
  const usersUpdate = (
    id: string,
    updateUserDto: UpdateUserDto,
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<null>(
      {url: `/admin/users/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateUserDto
    },
      options);
    }
  const usersDelete = (
    id: string,
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<null>(
      {url: `/admin/users/${id}`, method: 'DELETE'
    },
      options);
    }
  const usersResetPassword = (
    id: string,
    resetPasswordDto: ResetPasswordDto,
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<null>(
      {url: `/admin/users/${id}/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPasswordDto
    },
      options);
    }
  const usersSetRoles = (
    id: string,
    setRolesDto: SetRolesDto,
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<null>(
      {url: `/admin/users/${id}/roles`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: setRolesDto
    },
      options);
    }
  return {usersGetAll,usersCreate,usersUpdate,usersDelete,usersResetPassword,usersSetRoles}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UsersGetAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersGetAll']>>>
export type UsersCreateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersCreate']>>>
export type UsersUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersUpdate']>>>
export type UsersDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersDelete']>>>
export type UsersResetPasswordResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersResetPassword']>>>
export type UsersSetRolesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersSetRoles']>>>
