/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * PhotoBank.Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * OpenAPI spec version: 1.0
 */
import type {
  ClaimDto,
  UpdateUserDto,
  UserWithClaimsDto
} from '../photoBankApiVersion1000CultureNeutralPublicKeyTokenNull.schemas';

import { photobankAxios } from '../../axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getUsers = () => {
const usersGetAll = (
    
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<UserWithClaimsDto[]>(
      {url: `/admin/users`, method: 'GET'
    },
      options);
    }
  const usersUpdate = (
    id: string,
    updateUserDto: UpdateUserDto,
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<null>(
      {url: `/admin/users/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateUserDto
    },
      options);
    }
  const usersSetClaims = (
    id: string,
    claimDto: ClaimDto[],
 options?: SecondParameter<typeof photobankAxios>,) => {
      return photobankAxios<null>(
      {url: `/admin/users/${id}/claims`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: claimDto
    },
      options);
    }
  return {usersGetAll,usersUpdate,usersSetClaims}};

type AwaitedInput<T> = PromiseLike<T> | T;

    type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type UsersGetAllResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersGetAll']>>>
export type UsersUpdateResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersUpdate']>>>
export type UsersSetClaimsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getUsers>['usersSetClaims']>>>
