name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: frontend

      - name: Lint
        run: pnpm lint
        working-directory: frontend

      - name: Run frontend tests
        run: pnpm test
        working-directory: frontend

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore .NET packages
        run: dotnet restore
        working-directory: backend

      - name: Run .NET tests
        run: dotnet test PhotoBank.sln --no-build
        working-directory: backend