name: Manual Backend CI

on:
  workflow_dispatch:
    inputs:
      run_integration_tests:
        description: "Run IntegrationTests as well"
        type: boolean
        required: false
        default: false

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: backend/**/*.csproj

      - name: Restore
        run: dotnet restore backend/PhotoBank.Backend.sln

      - name: Build (Release, no warn-as-error)
        run: dotnet build backend/PhotoBank.Backend.sln -c Release -p:TreatWarningsAsErrors=false --no-restore

      # Юнит-тесты
      - name: Test (Unit)
        run: |
          dotnet test backend/PhotoBank.UnitTests/PhotoBank.UnitTests.csproj \
            -c Release --no-build \
            --logger "trx;LogFileName=unittests.trx" \
            --results-directory ./TestResults

      # Интеграционные тесты — по флажку при запуске
      - name: Test (Integration) - optional
        if: ${{ inputs.run_integration_tests == true }}
        run: |
          dotnet test backend/PhotoBank.IntegrationTests/PhotoBank.IntegrationTests.csproj \
            -c Release --no-build \
            --logger "trx;LogFileName=integration.trx" \
            --results-directory ./TestResults

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: TestResults
          if-no-files-found: ignore