name: Manual CI

on:
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          # lock лежит в frontend/, путь указываем от корня репо
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install (workspace)
        run: pnpm install --frozen-lockfile

      - name: Lint / Test / Build (shared, frontend, telegram-bot)
        run: |
          set -euo pipefail
          export CI=true

          run_if() { # dir script
            node -e "const s=require('./$1/package.json').scripts||{}; process.exit(s['$2']?0:1)"
          }

          run_pkg() { # dir
            local pkg="$1"
            echo "::group::▶ ${pkg}"

            if run_if "${pkg}" lint; then
              pnpm -C "${pkg}" run lint
            else
              echo "• skip lint"
            fi

            if run_if "${pkg}" test:ci; then
              pnpm -C "${pkg}" run test:ci
            elif run_if "${pkg}" test; then
              pnpm -C "${pkg}" run test
            else
              echo "• skip test"
            fi

            if run_if "${pkg}" build; then
              pnpm -C "${pkg}" run build
            else
              echo "• skip build"
            fi

            echo "::endgroup::"
          }

          run_pkg packages/shared
          run_pkg packages/frontend
          run_pkg packages/telegram-bot