name: Manual Backend CI

on:
  workflow_dispatch: {}

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: backend/**/*.csproj

      - name: Restore
        run: dotnet restore backend/PhotoBank.Backend.sln

      - name: Build (Release, no warn-as-error)
        run: dotnet build backend/PhotoBank.Backend.sln -c Release -warnaserror- --no-restore