name: Shared CI

on:
  push:
    paths:
      - 'frontend/packages/shared/**'
      - '.github/workflows/shared.yml'
  pull_request:
    paths:
      - 'frontend/packages/shared/**'
      - '.github/workflows/shared.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - name: Install dependencies
        run: pnpm -w install
        working-directory: frontend
      - name: Build shared package
        run: pnpm --filter @photobank/shared build
        working-directory: frontend
      - name: Test shared package
        run: pnpm --filter @photobank/shared test
        working-directory: frontend
