name: Version

on:
  push:
    branches:
      - main

jobs:
  prepare:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install nbgv
        run: |
          dotnet tool install -g nbgv || dotnet tool update -g nbgv

      - name: Prepare release
        run: nbgv prepare-release

      - name: Commit version and tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add backend/version.json
          git commit -m "chore: prepare release [skip ci]" || echo "No changes"
          git tag v$(nbgv get-version -v SemVer2)
          git push origin HEAD
          git push origin --tags
